version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Great-Password
      ACCEPT_EULA: Y
